### ISSUE TITLE
Sometimes the operation does not respond during scan.

### ISSUE THREAD

**Issue by 1natsu172** [1natsu172/bluevery#33]
from #32 

> Peripheral一覧で、Connectボタンや戻るボタンなどの操作ができなくなることがある。(Scan の callbackに処理を持っていかれている？)

**Comment by 1natsu172** [comment]
@ytka デバッグしたところscan時にexpensiveなstateの変更が行われるせいで、ブロッキングが発生している様子でした。

`react-native-paper`のButtonを適当な場所に配置して連打しているとブロッキングが発生してmaterial designの波形バブルがブロックされます。
その上で、

https://github.com/1natsu172/bluevery/blob/e0381e95a9f63533733799ba86a6fc292b836c8e/src/blueveryCore.ts#L213-L214

ここをなにもやらないVoid関数に変えてあげるとスムーズに連打できるようになります。

まだ深く追ってないのでstateの変更をどうハンドリングしてパフォーマンスチューニングするから今後考えます 🤔

**Comment by ytka** [comment]
> @ytka デバッグしたところscan時にexpensiveなstateの変更が行われるせいで、ブロッキングが発生している様子でした。
> 
> `react-native-paper`のButtonを適当な場所に配置して連打しているとブロッキングが発生してmaterial designの波形バブルがブロックされます。
> その上で、
> 
> https://github.com/1natsu172/bluevery/blob/e0381e95a9f63533733799ba86a6fc292b836c8e/src/blueveryCore.ts#L213-L214
> 
> ここをなにもやらないVoid関数に変えてあげるとスムーズに連打できるようになります。
> 
> まだ深く追ってないのでstateの変更をどうハンドリングしてパフォーマンスチューニングするから今後考えます 🤔

このあたりのコードを追いきれてはいないのですが、スキャンで検出する頻度が高すぎるのだとしたら、BleManagerのパラメータで制御可能であれば頻度を落とす、もしくは検出イベントを受信する側で Trottlingする必要があるのかもしれませんね。そして後者のほうが BleManagerの実装に依存しなくて良いので長期的にみて安定するのかもしれません。
(そういえば、私の環境で無反応になったときは多数の Peripheralを検出しているようでした)

一方で、某プロジェクトで同じ問題が起きていたかというと、そちらではスキャン検出時に特定の条件にマッチしたらそこでスキャンを停止し状態を更新、マッチしない場合は何もしないという制御だったため、今回のような問題は起きていなかったようです。このような使い方が主になるならのなら、上に書いた頻度の問題は後回しでもよいのかもしれません。

**Comment by 1natsu172** [comment]
@ytka 
そうですね。実際のユースケースだとscanのパラメータでUUID絞り込むと思うのでそんなに問題ないかもです。

reactアプリケーション側でre-render抑制してもらうのもありですし、bluevery側でなにかしらやるなら、stateへ反映するのをthrottleするかn秒間に検出したperipheralをキューに貯めてから一気にstateに入れるという感じになるかなと。

**Comment by ytka** [comment]
私の環境だと、なぜかこの問題が頻発して、Connectボタンや戻るボタンが反応しなくなるのと、"Attemped to remoe more BleManager listneres than added" エラーが発生するため、example追加の前に、もう少しこのあたりの挙動を追ってみます。
後者の問題は、https://github.com/1natsu172/bluevery/pull/37 で起きていたやつだったかも。

**Comment by ytka** [comment]
"Attemped to remoe more BleManager listneres than added"  は、connectボタンが押されたことがトリガーとなって発生するようです。
直後に発生することもあれば、だいぶ時間が経ってから発生することもありました。
時間が経ってから発生する場合は onDiscoverのログが大量に流れているので、BLEデバイスの検出通知が大量にスタックされているようです。
かなり短い間隔で onDisover通知がたくさん来るのだとしたら、一定時間バッファ(300msecくらい？)して peripheralごとの最新の通知だけをstateに反映するなどの工夫が必要かもしれないですね。

**Comment by 1natsu172** [comment]
@ytka 
ありがとうございます。
onDiscoverはble-managerがscan時にperipheralを見つけたら発火します。
それで、見つけたperipheralの情報を`scannedPeripherals`に詰めているので、ここでrerenderが暴発しまくっているんだと予想してます。

ちなみにdiscoverが発火する要因のひとつに、個々のperipheralの持っているrssi値が常に変わるからじゃないかとも思っています。scan画面に並ぶ個々のperipheralのrssiを見ると、頻繁に変更が見られるはずです。

パフォーマンスチューニングのイメージ少し出てきたので、僕も手元でチューニングやってみます。

**Comment by 1natsu172** [comment]
`Attemped to remove more BleManager listneres than added`

のエラーに関しては先日PRで直してもらったやつでは根治出来てなかったということですかね、、、🤔

**Comment by ytka** [comment]
> ちなみにdiscoverが発火する要因のひとつに、個々のperipheralの持っているrssi値が常に変わるからじゃないかとも思っています。scan画面に並ぶ個々のperipheralのrssiを見ると、頻繁に変更が見られるはずです。

rssi値の変化も原因の一つと思います。その他、onDiscover通知には Peripheral そのものが含まれているようだったので、peripheral.advertising.txPowerLevel も影響しているかもしれません。(stateにセットするときにここを切り捨てていれば関係ないかも)

**Comment by ytka** [comment]
> `Attemped to remove more BleManager listneres than added`
> 
> のエラーに関しては先日PRで直してもらったやつでは根治出来てなかったということですかね、、、🤔

と思ってたのですが、メッセージをよく読むと、追加されたリスナーより多くのリスナーを削除しているっぽいので、また別のケースかも・・・・
過剰にリスナーを削除しているのですかも。
前に直したのは component unmount時に起きる問題だったのでタイミンが異なっていて、connectするタイミングでこれが発生するのだとしたら、怪しそうなのは peripheral discovery 周りの通知を解除する処理あたりでしょうか。(そういう解除の実装が入っているとしたらですが)

**Comment by 1natsu172** [comment]
@ytka #49 をマージしました。コールで話したように`rssi`や`powerLevel`を捨てて、すでに`scannedPeripherals`にperipheralがあったらsetしないようにしています。
僕の手元だとまあまあブロッキング減った感あります。1度試してみてください。

**Comment by ytka** [comment]
> @ytka #49 をマージしました。コールで話したように`rssi`や`powerLevel`を捨てて、すでに`scannedPeripherals`にperipheralがあったらsetしないようにしています。
> 僕の手元だとまあまあブロッキング減った感あります。1度試してみてください。

ありがとうございます！確認してみます。

**Comment by ytka** [comment]
@1natsu172 ブロッキングが減って、ちゃんと反応するようになりました。ありがとうございます 🙏 

ブロッキングがなくなった結果、試せるようになってわかったことですが、
``Attemped to remove more BleManager listneres than added``
が発生するのは、stopScan()が原因のようです。
以下のように onConnectのタイミングで stopScan()してみたのですが、stopScan()を呼んではいけないタイミングだったりするのでしょうか？


```
  const onConnectPeripheral = useCallback(
    async (peripheralInfo: PeripheralInfo) => {
      try {
        await bluevery.stopScan();
        await bluevery.connect({
          connectParams: [peripheralInfo.id],
          retrieveServicesParams: [peripheralInfo.id],
          bondingParams: [peripheralInfo.id, peripheralInfo.id],
        });
```

**Comment by 1natsu172** [comment]
@ytka `stopScan`で`cleanupScan`が呼ばれそこで`discoverListener`をremoveしてるんですが、ここの実装で心当たりあるので直してみます

**Comment by 1natsu172** [comment]
@ytka #50 で `Attemped to remove more BleManager listneres than added` 修正してみました 🙏

**Comment by ytka** [comment]
> @ytka #50 で `Attemped to remove more BleManager listneres than added` 修正してみました 🙏

ありがとうございます。stopScan()しても落ちなくなりました 🙏 
Scan用のイベントリスナーを解除する必要があったのですね。なるほど。

**Comment by 1natsu172** [comment]
close by #49
