### ISSUE TITLE
Build error: TS4023

### ISSUE THREAD

**Issue by ytka** [1natsu172/bluevery#8]
## 現象
ビルドすると toTimeoutPromise の戻り値型に対して TS4023エラーが発生する。

## 修正方法
p-timeout の ClearablePromise は p-timeout ver 4系では export されておらず非公開だが、toTimeoutPromise の戻り値は型推論で ClearablePromise が含まれていることが原因と推測した。
以下のように toXXXPromise の戻り値型に対してアノテーションを付与したところビルドに成功した。
https://github.com/ytka/bluevery/commit/9f4987934d0bede2444189f8910e2719781d72fc

## 別の修正方法
p-timeout ver 5系では ClearablePromise が export されているのでこちらに置き換えることでもエラーは発生しなくなる。
ただし、jestで p-timeout の import 時に  SyntaxError が発生する。こちらの問題は babel などを修正してみたが、うまく回避できなかった。

**Comment by 1natsu172** [comment]
@ytka 

p-timeoout v5 出てるの知らなかったです。上げる方向で行きたいです。
Jestでエラーが出るのは、たぶんEMSオンリーになったからだと思うので、なにかしら直せばいけるのではと思っています 📦

**Comment by 1natsu172** [comment]
@ytka https://github.com/1natsu172/bluevery/commit/2e590e05147647a8bad080c866351f9ae080c1e7
master直Pushですが、v5対応しました。
